### PR TITLE
updated some packages, but some still failing audit due to deps of deps.

### PR DESCRIPTION
**Pull request by joebligblog**
Hi David.
I'm working on Fuge for Peter Elgar in FourTheorem. I was updating packages, and Spacey Standard is failing npm audit due to dependencies of dependencies.. etc.
Peter asked me to create a pull request and mention it to you. I think he said he was going to contact you at some stage about it himself.

Thanks,
Joe

### CODE REVIEW

**Review by davidmarkclements — CHANGES_REQUESTED** [review]
Can you pr the package.json only - no package-lock on modules (only good for apps)

**Comment by davidmarkclements** [comment]
Hey @gijoe50000 I've invited you as collab for this on gh and npm - feel free to merge and publish once request for change is complete :+1:

**Comment by joebligblog** [comment]
Hi Dave. 
Nice one.
I'll dig into it there later.
Thanks,
Joe

**Comment by joebligblog** [comment]
Hi Dave. 

Spacey is now passing npm audit, so I merged it there a few minutes ago. I used a 3rd party build of Fixpack, that someone else uploaded, as the author doesn't seem to be maintaining it, and I replaced Standard-Format (deprecated) with Standard in dependencies. Seems to be working fine anyway.
Let me know if there's any problems.

Thanks,
Joe

**Pull request merged**
